name: Main Test

on: [push]

jobs:
  Test: # jobs의 이름
    runs-on: ubuntu-latest # 우분투 최신 버전 사용

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python Version 3.x
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. Install library
      - name: Install library
        run: pip install -r requirements.txt

      # 4. Start Testing
      - name: Start Training
        run: python main.py
