name: Main Test

on: [push]

jobs:
  Test: # jobs의 이름
    runs-on: ubuntu-latest # 우분투 최신 버전 사용

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']  # 여러 Python 버전 지정
        
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python Version 3.x
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}  # 각 버전으로 테스트

      # 3. Install library
      - name: Install library
        run: |
           pip install tensorflow==2.10
           pip install numpy==1.21

      # 4. Start Testing
      - name: Start Training
        run: python main.py
